version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-mcp-demo
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Uncomment the following section if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama-data:
    driver: local

# Optional: Add a simple web UI for testing
# Uncomment the section below if you want a web interface
#
#  ollama-webui:
#    image: ghcr.io/open-webui/open-webui:main
#    container_name: ollama-webui
#    ports:
#      - "3000:8080"
#    environment:
#      - OLLAMA_BASE_URL=http://ollama:11434
#    depends_on:
#      - ollama
#    volumes:
#      - open-webui:/app/backend/data
